[project]
version="0.1"
name="pokemonrates"
dependencies = [
	"mastodon.py",
	"requests",
	"ruamel.yaml",
	"tracery",
	"beautifulsoup4",
]
requires-python=">=3.12"

[dependency-groups]
test = [
	"pytest",
	"coverage[toml]",
]
