# This is a basic workflow to help you get started with Actions

name: Scrape pokémon list

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "20 4 * * *"
  push:
    branches:
      - master

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: 'pipenv'
    - name: Install pipenv
      run: pipx install pipenv
    - run: pipenv sync -d
    - run: pipenv run python scrape_pokemon.py > pokemon-2.txt
    - id: compare
      run:  if [[ $(wc -l < pokemon.txt) -lt $(wc -l < pokemon-2.txt) ]]; then echo "changed=1" >> $GITHUB_ENV; fi
    - name: Commit and push
      if: ${{ env.changed == 1 }}
      run: |
        mv pokemon-2.txt pokemon.txt
        git config user.email "codl@codl.fr"
        git config user.name "codl"
        git commit -m "Update list of pokémon" --author="Actions <actions@github.com>" pokemon.txt
        git push --force origin master:update-scrape
    - name: pull-request-action
      if: ${{ env.changed == 1 }}
      uses: vsoch/pull-request-action@1.0.18
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_BRANCH: "master"
        PULL_REQUEST_FROM_BRANCH: "update-scrape"
        PULL_REQUEST_ASSIGNEES: "codl"
        PULL_REQUEST_TITLE: "Update list of pokémon"
