name: Scrape pokémon list

on:
  schedule:
    - cron: "20 4 * * 1,4"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11.1"
        cache: 'pip'
    - run: pip install -r ci-requirements.txt
    - run: pip install -r requirements.txt
    - run: python scrape_pokemon.py > pokemon.txt
    - id: compare
      run: git diff --quiet pokemon.txt || echo "changed=1" >> $GITHUB_ENV
    - name: Commit and push
      if: ${{ env.changed == 1 }}
      run: |
        git config user.email "codl@codl.fr"
        git config user.name "codl"
        git commit -m "Update list of pokémon" --author="Actions <actions@github.com>" pokemon.txt
        git push --force origin master:update-scrape
    - name: pull-request-action
      if: ${{ env.changed == 1 }}
      uses: vsoch/pull-request-action@1.0.24
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_BRANCH: "master"
        PULL_REQUEST_FROM_BRANCH: "update-scrape"
        PULL_REQUEST_ASSIGNEES: "codl"
        PULL_REQUEST_TITLE: "Update list of pokémon"
