name: Run tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11.1"
        cache: 'pip'
    - name: Install pip-tools
      run: pip install -r ci-requirements.txt
    - run: pip-sync dev-requirements.txt requirements.txt
    - run: python -m pytest
