name: Run tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11.1"
        cache: 'pip'
    - run: pip install -r ci-requirements.txt
    - run: pip install -r dev-requirements.txt -r requirements.txt
    - run: python -m pytest
